### ISSUE TITLE
cannot connect

### ISSUE THREAD

**Issue by zillerium** [subhodi/ipfs-cluster-private#1]
ipfs-cluster-B | 17:30:08.497  INFO    restapi: REST API (libp2p-http): ENABLED. Listening on:
ipfs-cluster-B |         /ip4/127.0.0.1/tcp/9096/p2p/12D3KooWGYJUBJq4nBpHudqDMicSGkWnpTu1eVNhVPoeEybQ8ywE
ipfs-cluster-B |         /ip4/172.18.0.5/tcp/9096/p2p/12D3KooWGYJUBJq4nBpHudqDMicSGkWnpTu1eVNhVPoeEybQ8ywE
ipfs-cluster-B | 
ipfs-cluster-B |  restapi.go:523
ipfs-cluster-B | 17:30:08.497  INFO  ipfsproxy: IPFS Proxy: /ip4/127.0.0.1/tcp/9095 -> /ip4/127.0.0.1/tcp/5001 ipfsproxy.go:303
ipfs-cluster-B | 17:30:08.497  INFO    restapi: REST API (HTTP): /ip4/127.0.0.1/tcp/9094 restapi.go:501
ipfs-cluster-B | 17:30:08.497  INFO       crdt: crdt Datastore created. Number of heads: 0. Current max-height: 0 crdt.go:262
ipfs-cluster-B | 17:30:08.497  INFO       crdt: 'trust all' mode enabled. Any peer in the cluster can modify the pinset. consensus.go:263
ipfs-cluster-B | 17:30:08.497  INFO    cluster: Cluster Peers (without including ourselves): cluster.go:613
ipfs-cluster-B | 17:30:08.497  INFO    cluster:     - No other peers cluster.go:615
ipfs-cluster-B | 17:30:08.497  INFO    cluster: ** IPFS Cluster is READY ** cluster.go:628
ipfs-cluster-B | 17:30:08.498 ERROR   ipfshttp: error posting to IPFS: Post http://127.0.0.1:5001/api/v0/repo/stat?size-only=true: dial tcp 127.0.0.1:5001: connect: connection refused ipfshttp.go:563
ipfs-cluster-B | 17:30:08.498 ERROR   ipfshttp: Post http://127.0.0.1:5001/api/v0/repo/stat?size-only=true: dial tcp 127.0.0.1:5001: connect: connection refused ipfshttp.go:747
ipfs-cluster-B | 17:30:08.498 ERROR  p2p-gorpc: Post http://127.0.0.1:5001/api/v0/repo/stat?size-only=true: dial tcp 127.0.0.1:5001: connect: connection refused call.go:64
ipfs-cluster-B | 17:30:08.498 ERROR   diskinfo: Post http://127.0.0.1:5001/api/v0/repo/stat?size-only=true: dial tcp 127.0.0.1:5001: connect: connection refused disk.go:96
ipfs-cluster-B | 17:30:08.498 WARNI    monitor: discarding invalid metric: &{Name:freespace Peer:12D3KooWGYJUBJq4nBpHudqDMicSGkWnpTu1eVNhVPoeEybQ8ywE Value:0 Expire:1572715838498896477 Valid:false ReceivedAt:0} pubsubmon.go:193

**Comment by subhodi** [comment]
#2  Fixed it.
